# Generated by Django 4.0.7 on 2024-01-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_alter_friendlist_id_alter_friendrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
